#!/bin/sh -e

case "$1" in
    purge)

        rm -f /var/log/mythtv/mythbackend.log*
        if test -d /var/log/mythtv; then
          rmdir --ignore-fail-on-non-empty /var/log/mythtv
        fi

        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)


        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
